### ISSUE TITLE
商品预定功能

### ISSUE THREAD

**Issue by zcg66** [a6678696/a6678696.github.io#521]
![56](https://user-images.githubusercontent.com/98937245/164224016-e3f99f1d-6386-452d-a1bc-9ec88d43dd30.jpg)
![57](https://user-images.githubusercontent.com/98937245/164224022-354e8a08-acbc-4ab0-9ce1-7a3c66968944.jpg)
交易完成后，预订的用户那边商品状态没被刷新，这是bug还是我环境没配好导致的啊？在idea里也没看到有报错

**Comment by a6678696** [comment]
这个问题，前两天已经解决了，你的代码是之前的吧，使用最新的代码即可，你提问不要另开一个issue，直接在博客下面留言即可，如何上传图片查看提问要求那里

**Comment by a6678696** [comment]
https://github.com/a6678696/SecondHandTrade/commit/e3068e696e86c4ed806584899a5793bfc3edd4e3
上面是代码的变化
